// ============================================================================
// Covenant — Client-side Prover
// ============================================================================
// Orchestrates proof generation:
//   1. Generate credential_secret client-side (browser crypto)
//   2. Send witness to proving API (server-side bb prove simulation)
//   3. Receive 256-byte UltraHonk proof + public inputs
//   4. Optionally verify off-chain before submitting on-chain
//
// In production: the witness stays client-side, only the proof request is sent.
// The proving API never sees the raw KYC data — only derived hashes.
// ============================================================================

const API_BASE = import.meta.env.BASE_URL + "api";

export interface CredentialWitness {
  kycProvider: string;
  riskScore: number;
  sourceOfFunds: string;
  country: string;
  credentialSecret: string; // 32-byte hex — generated by SubtleCrypto
}

export interface ProofResult {
  proof: string;          // 256-byte hex
  publicInputs: string[]; // [nullifier, tier_bytes, address_commitment, view_key_hash]
  witness: {
    nullifier: string;
    tier: number;
    addressCommitment: string;
    viewKeyHash: string;
    kycLeaf: string;
    merkleRoot: string;
    expiryTimestamp: number;
    riskScore: number;
    kycProvider: string;
    sourceOfFunds: string;
    country: string;
  };
  metadata: {
    proofSystem: string;
    curve: string;
    circuitName: string;
    constraintCount: number;
    proofSizeBytes: number;
    barretenbergVersion: string;
    generatedAt: string;
  };
}

export interface SettlementProofResult {
  proof: string;
  publicInputs: string[];
  witness: {
    settlementHash: string;
    senderCommitment: string;
    recipientCommitment: string;
    amountCommitment: string;
    viewKeyHash: string;
    fromAsset: string;
    toAsset: string;
    amount: string | number;
    timestamp: number;
    tier: number;
  };
}

export interface VerifyResult {
  valid: boolean;
  checks: Record<string, boolean>;
  transcript: string;
  proofHash: string;
  verifiedAt: string;
}

// ── Generate credential proof ─────────────────────────────────────────────────
export async function proveCredential(witness: CredentialWitness): Promise<ProofResult> {
  const resp = await fetch(`${API_BASE}/prove/credential`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(witness),
  });
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({ error: resp.statusText }));
    throw new Error(`Prove API error: ${err.error || resp.statusText}`);
  }
  return resp.json();
}

// ── Generate settlement proof ─────────────────────────────────────────────────
export async function proveSettlement(params: {
  fromAsset: string;
  toAsset?: string;
  amount: string | number;
  complianceNullifier: string;
  credentialSecret?: string;
}): Promise<SettlementProofResult> {
  const resp = await fetch(`${API_BASE}/prove/settlement`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(params),
  });
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({ error: resp.statusText }));
    throw new Error(`Prove API error: ${err.error || resp.statusText}`);
  }
  return resp.json();
}

// ── Verify proof off-chain ────────────────────────────────────────────────────
export async function verifyProofOffChain(
  proof: string,
  publicInputs: string[],
  circuitType: "compliance" | "settlement" = "compliance"
): Promise<VerifyResult> {
  const resp = await fetch(`${API_BASE}/verify`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ proof, publicInputs, circuitType }),
  });
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({ error: resp.statusText }));
    throw new Error(`Verify API error: ${err.error || resp.statusText}`);
  }
  return resp.json();
}

// ── Credential secret management ─────────────────────────────────────────────
// IndexedDB-backed encrypted storage for credential secrets.
// Uses SubtleCrypto AES-256-GCM with a user-derived encryption key.

const DB_NAME = "covenant_secrets";
const STORE_NAME = "credentials";
const DB_VERSION = 1;

async function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = (e) => {
      const db = (e.target as IDBOpenDBRequest).result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME, { keyPath: "id" });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function deriveKey(passphrase: string, salt: Uint8Array): Promise<CryptoKey> {
  const baseKey = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(passphrase),
    "PBKDF2",
    false,
    ["deriveKey"]
  );
  return crypto.subtle.deriveKey(
    { name: "PBKDF2", salt, iterations: 100_000, hash: "SHA-256" },
    baseKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"]
  );
}

export interface StoredCredential {
  id: string;
  nullifier: string;
  tier: number;
  expiresAt: number;
  encryptedSecret: ArrayBuffer;
  iv: Uint8Array;
  salt: Uint8Array;
  kycProvider: string;
  issuedAt: number;
  renewedCount: number;
}

export async function storeCredentialSecret(
  credentialId: string,
  secret: string, // 32-byte hex
  metadata: {
    nullifier: string;
    tier: number;
    expiresAt: number;
    kycProvider: string;
    passphrase?: string;
  }
): Promise<void> {
  const passphrase = metadata.passphrase ?? "covenant_default_v1";
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const key = await deriveKey(passphrase, salt);

  const secretBytes = new Uint8Array(
    secret.replace("0x", "").match(/.{2}/g)!.map(h => parseInt(h, 16))
  );
  const encryptedSecret = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, secretBytes);

  const db = await openDB();
  const tx = db.transaction(STORE_NAME, "readwrite");
  const entry: StoredCredential = {
    id: credentialId,
    nullifier: metadata.nullifier,
    tier: metadata.tier,
    expiresAt: metadata.expiresAt,
    encryptedSecret,
    iv,
    salt,
    kycProvider: metadata.kycProvider,
    issuedAt: Math.floor(Date.now() / 1000),
    renewedCount: 0,
  };
  tx.objectStore(STORE_NAME).put(entry);
  await new Promise<void>((res, rej) => { tx.oncomplete = () => res(); tx.onerror = () => rej(tx.error); });
}

export async function retrieveCredentialSecret(
  credentialId: string,
  passphrase = "covenant_default_v1"
): Promise<{ secret: string; metadata: Omit<StoredCredential, "encryptedSecret" | "iv" | "salt"> } | null> {
  const db = await openDB();
  const tx = db.transaction(STORE_NAME, "readonly");
  const stored: StoredCredential | undefined = await new Promise((res, rej) => {
    const req = tx.objectStore(STORE_NAME).get(credentialId);
    req.onsuccess = () => res(req.result);
    req.onerror = () => rej(req.error);
  });
  if (!stored) return null;

  const key = await deriveKey(passphrase, stored.salt);
  const decrypted = await crypto.subtle.decrypt({ name: "AES-GCM", iv: stored.iv }, key, stored.encryptedSecret);
  const secretHex = Array.from(new Uint8Array(decrypted)).map(b => b.toString(16).padStart(2, "0")).join("");

  const { encryptedSecret: _, iv: __, salt: ___, ...meta } = stored;
  return { secret: "0x" + secretHex, metadata: meta };
}

export async function listStoredCredentials(): Promise<Omit<StoredCredential, "encryptedSecret" | "iv" | "salt">[]> {
  const db = await openDB();
  const tx = db.transaction(STORE_NAME, "readonly");
  const all: StoredCredential[] = await new Promise((res, rej) => {
    const req = tx.objectStore(STORE_NAME).getAll();
    req.onsuccess = () => res(req.result);
    req.onerror = () => rej(req.error);
  });
  return all.map(({ encryptedSecret: _, iv: __, salt: ___, ...meta }) => meta);
}

export async function deleteStoredCredential(credentialId: string): Promise<void> {
  const db = await openDB();
  const tx = db.transaction(STORE_NAME, "readwrite");
  tx.objectStore(STORE_NAME).delete(credentialId);
  await new Promise<void>((res, rej) => { tx.oncomplete = () => res(); tx.onerror = () => rej(tx.error); });
}

// ── Issuer root API ───────────────────────────────────────────────────────────
export async function fetchIssuerRoot() {
  const resp = await fetch(`${API_BASE}/issuer-root`);
  if (!resp.ok) throw new Error("Failed to fetch issuer root");
  return resp.json();
}

export async function signIssuerRootUpdate(newRoot: string, label: string, adminKey: string) {
  const resp = await fetch(`${API_BASE}/issuer-root`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ newRoot, label, adminKey }),
  });
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({}));
    throw new Error(`Issuer root update failed: ${(err as any).error || resp.statusText}`);
  }
  return resp.json();
}

// ── Credential renewal helpers ─────────────────────────────────────────────────
export function isEligibleForRenewal(expiresAt: Date): boolean {
  const now = Date.now();
  const expiry = expiresAt.getTime();
  const gracePeriodMs = 7 * 24 * 60 * 60 * 1000; // 7 days
  return now >= expiry - gracePeriodMs && now <= expiry;
}

export function daysUntilExpiry(expiresAt: Date): number {
  const now = Date.now();
  const diff = expiresAt.getTime() - now;
  return Math.max(0, Math.ceil(diff / (1000 * 60 * 60 * 24)));
}

export function getExpiryStatus(expiresAt: Date): "valid" | "expiring_soon" | "expired" | "renewable" {
  const days = daysUntilExpiry(expiresAt);
  if (days <= 0) return "expired";
  if (isEligibleForRenewal(expiresAt)) return "renewable";
  if (days <= 14) return "expiring_soon";
  return "valid";
}
