// ============================================================================
// Regulatory Export Routes — SAR / STR / CSV
// ============================================================================
// Covenant generates structured regulatory reports for compliance purposes.
//
// POST /api/export/sar  — FinCEN Suspicious Activity Report (JSON + CSV)
// POST /api/export/str  — FATF Suspicious Transaction Report (JSON + XML)
// POST /api/export/csv  — Generic CSV export for regulator portals
//
// Privacy design: Raw Stellar addresses are NEVER included.
// Only Poseidon2 commitments and compliance tiers appear in reports.
// Regulators use view keys to decrypt counterparty information.
// ============================================================================

import { Router } from "express";

const router = Router();

interface SettlementEntry {
  settlementId: string;
  complianceTier: number;
  amount: string;
  asset: string;
  timestamp: string;
  kycProvider?: string;
  sanctionsStatus?: string;
  riskScore?: number;
  jurisdiction?: string;
  senderCommitment?: string;
  viewKeyHash?: string;
}

// ── XML escaping — prevents XML injection via user-controlled fields ────────
// Any settlement field (asset, amount, kycProvider, etc.) can originate from
// client input; without escaping, values like `]]>`, `<`, `&` can break the
// document structure or inject spoofed elements into a regulator-facing report.
function escapeXml(value: unknown): string {
  return String(value ?? "").replace(/[<>&'"]/g, (ch) => {
    switch (ch) {
      case "<": return "&lt;";
      case ">": return "&gt;";
      case "&": return "&amp;";
      case "'": return "&apos;";
      case '"': return "&quot;";
      default: return ch;
    }
  });
}

// ── SAR XML helper ────────────────────────────────────────────────────────────
function buildSARXml(
  settlements: SettlementEntry[],
  filingInfo: { regulatorId: string; jurisdiction: string; filingDate: string }
): string {
  const txs = settlements
    .map(
      (s) => `    <Transaction>
      <TransactionID>${escapeXml(s.settlementId)}</TransactionID>
      <AssetType>${escapeXml(s.asset)}</AssetType>
      <AmountBand>${escapeXml(s.amount)}</AmountBand>
      <ComplianceTier>${escapeXml(s.complianceTier)}</ComplianceTier>
      <KYCProvider>${escapeXml(s.kycProvider ?? "Verified")}</KYCProvider>
      <SanctionsStatus>${escapeXml(s.sanctionsStatus ?? "Cleared")}</SanctionsStatus>
      <RiskScore>${escapeXml(s.riskScore ?? "N/A")}</RiskScore>
      <Timestamp>${escapeXml(s.timestamp)}</Timestamp>
      <SuspiciousActivity>None — ZK-attested compliance</SuspiciousActivity>
      <PrivacyNote>Sender identity protected by ZK proof. Provide view key to decrypt.</PrivacyNote>
    </Transaction>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<SuspiciousActivityReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://covenant.zk/schema/sar/v1.0">
  <FilingMetadata>
    <ReportType>Suspicious Activity Report (SAR)</ReportType>
    <FilingDate>${escapeXml(filingInfo.filingDate)}</FilingDate>
    <FilingInstitution>Covenant ZK Compliance System v1.0</FilingInstitution>
    <RegulatorID>${escapeXml(filingInfo.regulatorId)}</RegulatorID>
    <Jurisdiction>${escapeXml(filingInfo.jurisdiction)}</Jurisdiction>
    <ProofSystem>UltraHonk BN254 (Noir 1.0-beta.9)</ProofSystem>
    <OnChainVerification>Stellar Soroban — CovenantSettlement contract</OnChainVerification>
  </FilingMetadata>
  <Transactions>
${txs}
  </Transactions>
  <ComplianceAttestation>
    All transactions verified via zero-knowledge proofs on Stellar blockchain.
    KYC compliance and sanctions screening proven without revealing personal data.
    This report was generated by Covenant ZK Compliance Infrastructure.
  </ComplianceAttestation>
</SuspiciousActivityReport>`;
}

// ── POST /api/export/sar ──────────────────────────────────────────────────────
router.post("/export/sar", async (req, res) => {
  try {
    const {
      settlements = [],
      regulatorId = "REGULATOR",
      jurisdiction = "FCA (UK)",
      includeXml = true,
    } = req.body;

    if (!Array.isArray(settlements)) {
      return res.status(400).json({ error: "settlements must be an array" });
    }

    const filingDate = new Date().toISOString();

    // ── JSON SAR ─────────────────────────────────────────────────────────────
    const sarJson = {
      reportType: "Suspicious Activity Report (SAR)",
      sarVersion: "FinCEN SAR Form v2.0 / FINTRAC STR Equivalent",
      filingDate,
      filingInstitution: "Covenant ZK Compliance System v1.0",
      regulatorId,
      jurisdiction,
      proofSystem: "UltraHonk BN254 (Noir 1.0-beta.9, Barretenberg 0.87.0)",
      onChainVerification: "Stellar Soroban Protocol 26",
      transactions: settlements.map((s: SettlementEntry) => ({
        transactionId: s.settlementId,
        assetType: s.asset,
        amountBand: s.amount,
        complianceTier: s.complianceTier,
        complianceTierLabel: ["", "Basic", "Bronze", "Silver", "Gold", "Platinum"][s.complianceTier] || "Unknown",
        kycProvider: s.kycProvider ?? "Verified",
        sanctionsStatus: s.sanctionsStatus ?? "Cleared",
        riskScore: s.riskScore ?? null,
        jurisdiction: s.jurisdiction ?? jurisdiction,
        timestamp: s.timestamp,
        suspiciousActivity: "None — ZK-verified compliance",
        kycVerified: true,
        sanctionsCleared: true,
        proofOnChain: true,
        privacyNote:
          "Sender/recipient Stellar addresses protected by Poseidon2 commitment scheme. " +
          "Use view key (poseidon2(credential_secret || regulator_pk)) to decrypt counterparty info.",
        senderCommitmentHint: s.senderCommitment
          ? `${s.senderCommitment.slice(0, 16)}…`
          : "Not provided",
      })),
      summary: {
        totalTransactions: settlements.length,
        suspiciousCount: 0,
        complianceRate: "100%",
        averageTier:
          settlements.length > 0
            ? (
                settlements.reduce((a: number, s: SettlementEntry) => a + s.complianceTier, 0) /
                settlements.length
              ).toFixed(1)
            : "N/A",
      },
      legalDisclaimer:
        "This report is generated by an automated ZK compliance system. " +
        "All compliance checks are cryptographically proven on Stellar blockchain. " +
        "Raw PII is never stored or transmitted by this system.",
    };

    // ── CSV SAR ───────────────────────────────────────────────────────────────
    const csvHeader =
      "Transaction ID,Asset,Amount Band,Compliance Tier,KYC Provider,Sanctions Status,Risk Score,Jurisdiction,Timestamp,Suspicious Activity";
    const csvRows = settlements.map((s: SettlementEntry) =>
      [
        s.settlementId,
        s.asset,
        s.amount,
        s.complianceTier,
        s.kycProvider ?? "Verified",
        s.sanctionsStatus ?? "Cleared",
        s.riskScore ?? "",
        s.jurisdiction ?? jurisdiction,
        s.timestamp,
        "None",
      ].join(",")
    );
    const csv = [csvHeader, ...csvRows].join("\n");

    const response: Record<string, unknown> = {
      success: true,
      format: "SAR",
      json: sarJson,
      csv,
      recordCount: settlements.length,
      generatedAt: filingDate,
    };

    if (includeXml) {
      response.xml = buildSARXml(settlements, { regulatorId, jurisdiction, filingDate });
    }

    return res.json(response);
  } catch (err: any) {
    return res.status(500).json({ error: err.message });
  }
});

// ── POST /api/export/str ──────────────────────────────────────────────────────
router.post("/export/str", async (req, res) => {
  try {
    const {
      settlements = [],
      regulatorId = "REGULATOR",
      jurisdiction = "FCA (UK)",
      threshold = 10000, // STR threshold (varies by jurisdiction)
    } = req.body;

    if (!Array.isArray(settlements)) {
      return res.status(400).json({ error: "settlements must be an array" });
    }

    const filingDate = new Date().toISOString();

    // STR only covers transactions above the reporting threshold
    const reportableSettlements = settlements.filter((s: SettlementEntry) => {
      const numAmount = parseFloat(String(s.amount).replace(/[^0-9.]/g, "")) || 0;
      return numAmount >= threshold || s.complianceTier >= 4; // High-tier always reported
    });

    const strReport = {
      reportType: "Suspicious Transaction Report (STR)",
      strVersion: "FATF Recommendation 20 Compliant",
      filingDate,
      filingInstitution: "Covenant ZK Compliance System v1.0",
      regulatorId,
      jurisdiction,
      reportingThreshold: `$${threshold.toLocaleString()}`,
      totalSettlementsReviewed: settlements.length,
      reportableTransactions: reportableSettlements.length,
      transactions: reportableSettlements.map((s: SettlementEntry) => ({
        transactionId: s.settlementId,
        assetType: s.asset,
        amountBand: s.amount,
        complianceTier: s.complianceTier,
        kycProvider: s.kycProvider ?? "Verified",
        sanctionsStatus: s.sanctionsStatus ?? "Cleared",
        riskScore: s.riskScore ?? null,
        timestamp: s.timestamp,
        suspiciousBehaviorIndicators: [],
        naturalPersonInvolved: true,
        legalPersonInvolved: false,
        cryptoAsset: true,
        valueTransferMethod: "Stellar Soroban ZK-attested settlement",
        complianceEvidence:
          "UltraHonk zero-knowledge proof on Stellar blockchain. " +
          "Proof hash queryable via CovenantSettlement contract.",
        privacyNote:
          "Counterparty addresses protected by Poseidon2 commitment. " +
          "Selective disclosure via view key upon court order.",
      })),
      fatfComplianceStatement:
        "This institution employs ZK proof technology for privacy-preserving compliance. " +
        "All transactions are cryptographically attested on-chain per FATF Virtual Asset guidance (2021). " +
        "Travel Rule compliance is enforced via ASP (Associated Set Provider) protocol.",
      generatedAt: filingDate,
    };

    // CSV for STR
    const csvHeader =
      "Transaction ID,Asset,Amount Band,Compliance Tier,KYC Provider,Sanctions Status,Timestamp,Reportable";
    const csvRows = settlements.map((s: SettlementEntry) => {
      const numAmount = parseFloat(String(s.amount).replace(/[^0-9.]/g, "")) || 0;
      const reportable = numAmount >= threshold || s.complianceTier >= 4;
      return [
        s.settlementId,
        s.asset,
        s.amount,
        s.complianceTier,
        s.kycProvider ?? "Verified",
        s.sanctionsStatus ?? "Cleared",
        s.timestamp,
        reportable ? "YES" : "NO",
      ].join(",");
    });

    return res.json({
      success: true,
      format: "STR",
      json: strReport,
      csv: [csvHeader, ...csvRows].join("\n"),
      reportableCount: reportableSettlements.length,
      totalReviewed: settlements.length,
      generatedAt: filingDate,
    });
  } catch (err: any) {
    return res.status(500).json({ error: err.message });
  }
});

export default router;
